version: "3"
services:
  postgres:
    image: postgres
    container_name: pipeline_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  server:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ishimyi/krioarmatura:latest
    container_name: pipeline_server
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
    environment:
      DB: ${DB}
      NODE_ENV: production
      CLIENT_URL: ${CLIENT_URL}
      PORT: 80
      PORT_HTTPS: 443
      PORT_HTTP: 80
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      COOKIE_SECURE: "true"
      COOKIE_HTTP_ONLY: "true"
      COOKIE_SAME_SITE: None
      COOKIE_MAX_AGE: 604800000
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_WATERMARK_ID: ${CLOUDINARY_WATERMARK_ID}
      CLOUDINARY_WATERMARK_OPACITY: ${CLOUDINARY_WATERMARK_OPACITY}
      CLOUDINARY_WATERMARK_SIZE: ${CLOUDINARY_WATERMARK_SIZE}
    restart: always
    volumes:
      - ./server/configs/ssl:/usr/src/app/configs/ssl
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
